# Horizontal Pod Autoscaler
# Scales pods when CPU exceeds 50%
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache              # which deployment to scale
  minReplicas: 1                  # minimum pods (even with no traffic)
  maxReplicas: 10                 # maximum pods (cap)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # scale up when CPU > 50%
