# Liveness Probe Demo
# This pod creates a /tmp/healthy file on start,
# then deletes it after 30 seconds (simulating a crash).
# The liveness probe checks if the file exists.
# When it's gone → probe fails → K8s restarts the container.
apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
    - name: app
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - touch /tmp/healthy;
          echo "App started - healthy!";
          sleep 30;
          rm /tmp/healthy;
          echo "App became unhealthy!";
          sleep 600
      livenessProbe:
        exec:
          command: ["cat", "/tmp/healthy"]   # check if file exists
        initialDelaySeconds: 5               # wait 5s before first check
        periodSeconds: 5                     # check every 5 seconds
        failureThreshold: 3                  # restart after 3 failures
