# CronJob - runs every minute (for demo purposes)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
spec:
  schedule: "*/1 * * * *"            # every 1 minute
  successfulJobsHistoryLimit: 3      # keep last 3 completed jobs
  failedJobsHistoryLimit: 1          # keep last 1 failed job
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox:latest
              command: ["/bin/sh", "-c"]
              args:
                - echo "CronJob triggered at $(date)";
                  echo "Hello from scheduled task!"
          restartPolicy: OnFailure
