# Dev patch: only 1 replica for dev (save resources)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: ENVIRONMENT
              value: development
