# Secret - stores MongoDB credentials
# Values are base64 encoded:
#   echo -n "admin" | base64         → YWRtaW4=
#   echo -n "password123" | base64   → cGFzc3dvcmQxMjM=
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=           # admin
  mongo-root-password: cGFzc3dvcmQxMjM=   # password123
