# Pod that reads Secret as environment variables
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: app
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - echo "DB_USERNAME=$DB_USERNAME";
          echo "DB_PASSWORD=$DB_PASSWORD";
          echo "Secrets loaded! Sleeping...";
          sleep 3600
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials     # Secret name
              key: DB_USERNAME         # Key inside the Secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
