# Secret - stores sensitive data (base64 encoded)
# To encode: echo -n "myvalue" | base64
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USERNAME: YWRtaW4=              # base64 of "admin"
  DB_PASSWORD: c3VwZXJzZWNyZXQxMjM=  # base64 of "supersecret123"
